server:
  port: 81
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.146.0.2:1433;databaseName=test;user=SA;password=yourStrong(Password
mybatis:
  mapper-locations: classpath:mapper/UserMapper.xml,classpath:mapper/CourseMapper.xml
logging:
  level:
    root: warn